name: fNIRS-mental-workload-classifiers
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - easydict=1.9
  - ipython=7.18.1
  - jupyter=1.0.0
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.1.3
  - python=3.8.8
  - pytorch=1.7.1
  - scikit-learn=0.24.2
  - scipy=1.6.1
  - seaborn=0.11.0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2
  - tqdm=4.59.0

